# Generated by Django 5.1.6 on 2025-02-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=100)),
                ('rebrick_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
