# Generated by Django 5.1.6 on 2025-02-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='pieces',
            field=models.IntegerField(default=0),
        ),
    ]
